### ISSUE TITLE
Activate Recipe not working

### ISSUE THREAD

**Issue by gajdur** [nklerk/nl.nielsdeklerk.neeo#11]
Hi Niels, trying to make a flow when doorbell on (fibaro relais) then activate a recipe "my recipe".
No luck, i cannot start recipes from homey. Any tips? Testing from Homey is working but recipe is not starting. Tnx, Gajdur.

**Comment by nklerk** [comment]
Try adding a simplelog card (using the simple log app) or a send message to mobile phone or say something crard. this way you can more easily debug if the flow itself is activated. If the test flow is working then I'm almost sure that the card in the If... column isn't working somehow. I switched from zwave to a cheap 433mhz doorbell device as the zwave doorbell was unreliable for me. maybe you are having the same issue. 

There are no known issues with the activate recipe card that I'm aware of, that doesn't say there are no issues off course but might help you find the root cause.

**Comment by nklerk** [comment]
@gajdur Did you solve the issue?

**Comment by gajdur** [comment]
Hi @nklerk , not yet. Going to try this days. I think Neeo is responding delayed but not sure, going to try this also.

**Comment by nklerk** [comment]
Yesterday I’ve pushed a new beta update. As soon as it’s approved then I’ll publish it. Normally takes one or two days. You might want to try that one to.

**Comment by gajdur** [comment]
Hi Niels and tnx for your App. Still trying to get my Neeo working with all my AV devices, ordered one lirc2 now for the nvidia shield 2017 standard, no time to wait for bluetooth.

**Comment by nklerk** [comment]
A lirc2 is a good solution and is never a waste of money.
